### Send POST request with json body
POST http://localhost:8888/api/rate
Content-Type: application/json
Acept: application/json

{

  "product": "Nike"
}

<> 2019-05-31T123631.200.json
<> 2019-05-31T105626.200.json
<> 2019-05-31T105559.200.json
<> 2019-05-30T084622.200.json

### Send POST request with json body
POST http://localhost:8888/api/rate
Content-Type: application/json
Acept: application/json

{
  "amount": 5,
  "product": "Adidas"
}

<> 2019-05-31T123631.200.json
<> 2019-05-31T105626.200.json
<> 2019-05-31T105559.200.json
<> 2019-05-30T084622.200.json

###
POST http://localhost:8888/questions
Content-Type: application/json
Acept: application/json

{
	"title":"How To use Postgres with Spring Boot",
	"description": "Need to know more details"
}

###
#http://localhost:8888/questions/{questionId}/answers
POST http://localhost:8888/questions/1000/answers
Content-Type: application/json
Acept: application/json

{
  "text":"For using Postgres with Spring Boot use https://www.callicoder.com/spring-boot-jpa-hibernate-postgresql-restful-crud-api-example/"
}

###
